### ISSUE TITLE
Card for 夜[よる] has incorrect pitch accent graph

### ISSUE THREAD

**Issue by Kirk-Fox** [amaank404/Core2k6k_All_in_one#2]
Hey, I'm not sure if you ever plan on making a v2 for this, but if you do, the card in the current deck for 夜[よる] uses the pitch accent graph for 夜[よ]. Thank you for this wonderful resource!

**Comment by amaank404** [comment]
Thanks for noticing the issue, i made the said changes and uploaded it into a v2
