### ISSUE TITLE
Pitch pattern not showing for dark mode on phone

### ISSUE THREAD

**Issue by RayanK95** [amaank404/Core2k6k_All_in_one#3]
Hey, the Pitch pattern picture seems to be working fine with darkmode for Anki Desktop but It doesn't seem to do so on Ankidroid as it goes black on black and only the white dots can be seen (as shown in the screenshot attached).
Thank you for your work!
![AnkiDroid_Darkmode](https://github.com/amaank404/Core2k6k_All_in_one/assets/101478587/6f3637f1-c6ff-4550-979e-0d81cec5a3cc)

**Comment by amaank404** [comment]
alright, give me a few hours as I fix the stylesheets and test it out on both desktop and mobile

**Comment by amaank404** [comment]
check the latest release v3 for the fixed deck. I have tested the changes both on desktop and mobile, both in light and dark mode.

![image](https://github.com/amaank404/Core2k6k_All_in_one/assets/71920621/c1dd9ef5-79d6-4c51-ab54-32b9c9f22548)

**Comment by amaank404** [comment]
you should be able to update ur deck by redownloading the decks and importing them. If an issue persists with that, **please let me know**
